### ISSUE TITLE
Continuous loop for: Importing values from excel and assigning them to variables, solving equations and outputing the solution of the equations

### ISSUE THREAD

**Issue by ShreeniketJoshi** [zhiwehu/Python-programming-exercises#101]
Hello community,
I'm a mechanical engineer, and quite new to github. I'm doing research in Thinfilms. For my project, I have to take my experimental values which are in excel sheet format and use a python code to substitute these values in analytical equations, solve them and output the answer in a new excel column. This code should run on a continuous loop and automatically calculate solution for each input value (present in the column)

I'm a beginner in python and tried searching the web for answers, can someone please give me a hint as to how I can go about this?
Thanks

**Comment by DSLYL** [comment]
Sorry,I can't do solve your problem.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ShreeniketJoshi"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 晚上11:37
收件人:&nbsp;"zhiwehu/Python-programming-exercises"<Python-programming-exercises@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[zhiwehu/Python-programming-exercises] Continuous loop for: Importing values from excel and assigning them to variables, solving equations and outputing the solution of the equations (#101)





 
Hello community,
 I'm a mechanical engineer, and quite new to github. I'm doing research in Thinfilms. For my project, I have to take my experimental values which are in excel sheet format and use a python code to substitute these values in analytical equations, solve them and output the answer in a new excel column. This code should run on a continuous loop and automatically calculate solution for each input value (present in the column)
 
I'm a beginner in python and tried searching the web for answers, can someone please give me a hint as to how I can go about this?
 Thanks
