### ISSUE TITLE
Request: Change 'he' references for 'he or she' :)

### ISSUE THREAD

**Issue by pilimayora** [zhiwehu/Python-programming-exercises#45]
https://github.com/zhiwehu/Python-programming-exercises/blob/22bb9b343f009a1d710117b02f5b278e0761094f/100%2B%20Python%20challenging%20programming%20exercises.txt#L7

**Comment by vasunep0306** [comment]
I fixed it. How do I submit a merge request?

**Comment by ashwanidv100** [comment]
Thank you for pointing out @pilimayora, You should revisit this [README] (https://github.com/ashwanidv100/Python-programming-exercises/blob/master/README.md).

**Comment by pilimayora** [comment]
Hey, no worries! Happy to contribute and very pleased with you guys actually taking a look at it. 
Btw, there are still some "He" references in the README.md, maybe one more commit?

**Comment by ashwanidv100** [comment]
I think it ok from now on!

**Comment by pilimayora** [comment]
👍
