### ISSUE TITLE
Why are the issues taking long to be resolved

### ISSUE THREAD

**Issue by koolamusic** [zhiwehu/Python-programming-exercises#51]
- this project is featured on the github explore page
**however, it does not have a verbose README**
**some issues and PR are taking too long to get attention**

**Comment by JonathanGrant92** [comment]
Agreed. This repository needs more contributors.

**Comment by mikeysan** [comment]
It is December, 2020. Once again (for the first time for me) GitHub recommended this repository, but sadly it seems that issues are still not getting closed or any responses.
