### ISSUE TITLE
AttributeError: 'recta' object has no attribute 'ar

### ISSUE THREAD

**Issue by mfloressv** [zhiwehu/Python-programming-exercises#95]
class recta():
    
    def __init__(self,base,heig):
        self.base=base
        self.heig=heig  

    def area(self):
        self.ar=self.base*self.heig
        
    def __str__(self):
        return "the area of this rectangle is : "+(self.ar)

my_rect = recta(2,2)
print(my_rect)

This is the error message that I received:

AttributeError: 'recta' object has no attribute 'ar'

I will appreciate any help on this matter

**Comment by luism1randa** [comment]
You didn’t assign ar in your constructor. Your init method should contain
all object attributes

**Comment by mfloressv** [comment]
could you give the example. I still dont get it

**Comment by luism1randa** [comment]
Your error says your "ar" attribute doesn't exist. Your current attributes are the ones under your init (your constructor). So you're attributes so far are "base" and "heig". To add the third attribute just add ar along with those like this:

`def __init__(self,base,heig):`
`   self.base=base`
`   self.heig=heig `
`   self.ar = None`

**Comment by mfloressv** [comment]
its a little bit strange but if I do that, I received different message:

class recta():
    
    def __init__(self,base,heig):
        self.base=base
        self.heig=heig
        self.ar= None

    def area(self):
        self.ar=self.base*self.heig
        
    def __str__(self):
        return "the area of this rectangle is : "+str(self.ar)

my_rect = recta(2,2)
print(my_rect)

Error message

TypeError: can only concatenate str (not "NoneType") to str

**Comment by luism1randa** [comment]
So there's a few bugs in your code. When you're declaring a class you
should capitalize the first letter and it does not have parentheses. You
also never called your area() method so you never actually changed the
self.ar attribute from None to a number. I highlighted the changes I made
to your code in red and it should work like this:

class Recta:

def __init__(self, base, heig):

self.base = base

self.heigh = heigh

self.ar = None


def area(self):

self.ar = self.base * self.heig

def __str__(self):

return "The area of this rectangle is: " + str(self.ar)

my_rect = Recta(2,2)

my_rect.area() <- You need to make sure you're calling this method or else
self.ar will stay as None

print(my_rect)


I hope that helps, let me know if you have any questions!

**Comment by mfloressv** [comment]
hey thank you
I appreciate your help on this.
you helped me  a lot
